# URL to the Prometheus rules API endpoint
rulesUrl: http://localhost:9090/api/v1/rules

# Polling interval in seconds
rulesPollingInterval: 3600

# Addr:port to Zabbix for where to send trapper discovery items
zabbixAddr: localhost:10051

# Zabbix items key prefix, keys will be zabbixKeyPrefix.alertname
zabbixKeyPrefix: prometheus
